### PR TITLE
add @danielballan

### PR DESCRIPTION
**Pull request by CJ-Wright**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Comment by tacaswell** [comment]
You beat me to pushing a fix to this by about 20 seconds!

**Comment by CJ-Wright** [comment]
Even on sabbatical I'm connected conda-forge
image

(credit to Matt Zeilinger, https://www.inprnt.com/gallery/m_zeilinger/android-project-beale/)

**Comment by CJ-Wright** [comment]
(although the movement of github shas is really annoying)

**Pull request merged**
