### PR TITLE
del @cj-wright

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by CJ-Wright** [comment]
@conda-forge/event-model

**Comment by CJ-Wright** [comment]
btw, this needs real maintainers since the maintainers can't be themselves

**Comment by mrakitin** [comment]
> btw, this needs real maintainers since the maintainers can't be themselves

Can you please clarify?

**Comment by CJ-Wright** [comment]
the maintainers need to be real people, not conda-forge/event-model, since that is circular

**Pull request merged**
